[package]
name = "codecrafters-shell"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.80"


[dependencies.rustyline]
version = "15.0.0"
features = ["derive"]
